Initial commit

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -1,6 +1,61 @@
 #!/usr/bin/env bash
 # bin/compile <build-dir> <cache-dir> <env-dir>
 
+BUILD_DIR=$1
+CACHE_DIR=$2
+BIN_DIR=$(cd $(dirname $0); pwd) # absolute path
+
+TEXLIVE_DOMAIN="https://heroku-buildpack-tex.s3.amazonaws.com"
+VERSION=`curl $TEXLIVE_DOMAIN/VERSION -s`
+TEXLIVE_URL="$TEXLIVE_DOMAIN/texlive-$VERSION.tar.gz"
+TEXLIVE_HOME=$BUILD_DIR/.texlive
+TEXLIVE_CACHE=$CACHE_DIR/.texlive
+PATH=$TEXLIVE_HOME/bin/x86_64-linux:$PATH
+PROFILE_D=$BUILD_DIR/.profile.d/texlive.sh
+
+# Output helpers
+source $BIN_DIR/utils
+
+# Prepare the various paths
+mkdir -p $TEXLIVE_HOME
+mkdir -p $TEXLIVE_CACHE
+mkdir -p `dirname $PROFILE_D`
+
+if [ -f $TEXLIVE_CACHE/VERSION ] && (( $VERSION == `cat $TEXLIVE_CACHE/VERSION` )); then
+    # Get TeX Live from the cache if possible
+    build-step "Installing TeX Live $VERSION from cache"
+    cp -R $TEXLIVE_CACHE/* $TEXLIVE_HOME
+else
+    # Get TeX Live from S3 if necessary
+    if [ -f "$TEXLIVE_CACHE/VERSION" ]; then
+        build-step "Upgrading to TeX Live $VERSION"
+    else
+        build-step "Fetching TeX Live $VERSION"
+    fi
+
+    curl $TEXLIVE_URL -s -o - | tar xzf - -C $TEXLIVE_HOME
+
+    # Make sure the cache is empty
+    rm -rf $TEXLIVE_CACHE/*
+
+    # Store a copy of it in the cache so it doesn't have to be fetched again
+    cp -R $TEXLIVE_HOME/* $TEXLIVE_CACHE
+
+    # Store the version for later
+    echo $VERSION > $TEXLIVE_CACHE/VERSION
+fi
+
+# Check for an essential binary to make sure it's installed
+if [ ! `which pdflatex` ]; then
+    build-warn "TeX Live installation failed"
+    exit 1
+fi
+
+# Set up the environment for runtimes now that compilation has finished
+echo 'export PATH=$HOME/.texlive/bin/x86_64-linux:$PATH' >> $PROFILE_D
+
+
+
 set -eo pipefail
 
 # Set Buildpack ENV Variables
@@ -16,6 +71,7 @@ TEXLIVE_DOMAIN="https://cah-buildpacks.s3.amazonaws.com"
 # VERSION=`curl $TEXLIVE_DOMAIN/PACKAGES-VERSION -s`
 VERSION=10;
 # # TEXLIVE_PACKAGES_URL="$TEXLIVE_DOMAIN/tex-packages-$VERSION.tar.gz"
+# https://storage.googleapis.com/app0124/cdn/tex-packages.tar.gz
 TEXLIVE_PACKAGES_URL="https://storage.googleapis.com/app0124/cdn/tex-packages.tar.gz"
 TEXLIVE_HOME=$BUILD_DIR/.texlive
 TEXLIVE_CACHE=$CACHE_DIR/.texlive
